Added quests.json and quests_vendor.json for quest rewards
brather1ng/RePoE pull request #17
Opened 2019-11-18 00:28 UTC by lherron

Hi, I've added extracts for quest rewards by quest plus class and by vendor.

2019-11-18 19:43 UTC, brather1ng commented
Thanks for the PR!

Please add docs files (and entries in the readme) for your new files. Documenting how the game data works in addition to providing it is a major part of this repo, imo.

Some other things I noticed from taking a quick look:

- If a value is already present as a key, it doesn't need to be repeated in its object (e.g. the quest ids). That's just redundant information.
- Since the code for the two files is pretty much independent, I'd prefer two separate Python files.
- Please remove commented out code.
- I don't like "All" as a class value. It's a hardcoded string with a special meaning every user has to implement. I'm not sure what the best solution would be here. What about skipping the classes entry instead?

2019-11-23 14:52 UTC, lherron commented
Finally had some free time to make the updates, let me know if this looks good.  Thanks!

2019-11-23 15:59 UTC, brather1ng requested changes
Looks mostly good now, just a few minor things.

2019-11-23 15:59 UTC, brather1ng commented on RePoE/parser/modules/quest_rewards.py
> +                        "type": reward_row["BaseItemTypesKey"]["ItemClassesKey"]["Name"]
I'd prefer the item class id over this so it's a direct reference to `item_classes.json`.

2019-11-23 15:59 UTC, brather1ng commented on RePoE/parser/modules/quest_rewards.py
> +        for state_row in relational_reader['QuestStates.dat']:
With vendor rewards in a separate file, this loop does nothing here.

2019-11-23 15:59 UTC, brather1ng commented on RePoE/parser/modules/vendor_rewards.py
> +        print(root)
This looks like output from your debugging and is a bit much for general logging. Probably doesn't hurt to remove all the prints from this file.

2019-11-23 18:29 UTC, lherron commented
Done!  Not sure how I missed those prints. ;-)

On Sat, Nov 23, 2019 at 9:59 AM brather1ng <notifications@github.com> wrote:

> *@brather1ng* requested changes on this pull request.
>
> Looks mostly good now, just a few minor things.
> ------------------------------
>
> In RePoE/parser/modules/quest_rewards.py
> <https://github.com/brather1ng/RePoE/pull/17#discussion_r349877706>:
>
> > +
> +                # Add an entry for the quest into the root node
> +                if questId not in root:
> +                    root[questId] = {
> +                        "name": reward_row["QuestKey"]["Name"],
> +                        "act": reward_row["QuestKey"]["Act"],
> +                        "rewards": {}
> +                    }
> +
> +                ##### This is for root->quest->rewards->class
> +                # Add an entry for the reward into the quest node
> +                if rewardName not in root[questId]["rewards"]:
> +                    root[questId]["rewards"][rewardId] = {
> +                        "classes": [],
> +                        "name": rewardName,
> +                        "type": reward_row["BaseItemTypesKey"]["ItemClassesKey"]["Name"]
>
> I'd prefer the item class id over this so it's a direct reference to
> item_classes.json.
> ------------------------------
>
> In RePoE/parser/modules/quest_rewards.py
> <https://github.com/brather1ng/RePoE/pull/17#discussion_r349878026>:
>
> > +                ##### This is for root->quest->rewards->class
> +                # Add an entry for the reward into the quest node
> +                if rewardName not in root[questId]["rewards"]:
> +                    root[questId]["rewards"][rewardId] = {
> +                        "classes": [],
> +                        "name": rewardName,
> +                        "type": reward_row["BaseItemTypesKey"]["ItemClassesKey"]["Name"]
> +                    }
> +                if charClass == "All":
> +                    root[questId]["rewards"][rewardId]["classes"] = all_classes
> +                else:
> +                    if charClass not in root[questId]["rewards"][rewardId]["classes"]:
> +                        root[questId]["rewards"][rewardId]["classes"].append(charClass)
> +
> +
> +        for state_row in relational_reader['QuestStates.dat']:
>
> With vendor rewards in a separate file, this loop does nothing here.
> ------------------------------
>
> In RePoE/parser/modules/vendor_rewards.py
> <https://github.com/brather1ng/RePoE/pull/17#discussion_r349878053>:
>
> > +                if charClass == "All":
> +                    root[npcId]["rewards"][rewardId]["classes"] = all_classes
> +                else:
> +                    if charClass not in root[npcId]["rewards"][rewardId]["classes"]:
> +                        root[npcId]["rewards"][rewardId]["classes"].append(charClass)
> +
> +                if ((npcName != "Lilly Roth") and (npcName != "Siosa")):
> +                    if reward_row["QuestState"] in all_quest_states:
> +                        root[npcId]["rewards"][rewardId]["quest_id"] = all_quest_states[reward_row["QuestState"]]
> +                    else:
> +                        # BLATANT KLUDGE: Quest state 244 = a2q6, but isn't in QuestStates.dat
> +                        if reward_row["QuestState"] == 244:
> +                            root[npcId]["rewards"][rewardId]["quest_id"] = "a2q6"
> +                print("Length of root: ", len(root))
> +                print("Length of root[", npcId, "][rewards]: ", len(root[npcId]["rewards"]))
> +        print(root)
>
> This looks like output from your debugging and is a bit much for general
> logging. Probably doesn't hurt to remove all the prints from this file.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/brather1ng/RePoE/pull/17?email_source=notifications&email_token=AAPPANX4IGRDDVPLTOMX5FDQVFHOPA5CNFSM4JOMSUKKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCMYA2JI#pullrequestreview-321916197>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAPPANSC62APVQC6EVBGLK3QVFHOPANCNFSM4JOMSUKA>
> .
>

2019-11-23 18:30 UTC, brather1ng approved these changes

2019-11-23 18:31 UTC, merged