add in json files to global variables
brather1ng/RePoE pull request #27
Opened 2020-05-12 08:04 UTC by NickRyder

Before I tried to be too slick by having it automatically detect the json files and add them into `global()`. This has the obvious downside of not being IDE compatible.

This PR:
- Explicitly loads in the json files on `__init__` (so they are in `global()`)
- Will give a warning if one of the json files doesnt load correctly
- Will give a fatal error if one of the json files in `\data` isn't represented in `__init__` with instructions to come fix it.

2020-05-12 16:19 UTC, brather1ng requested changes
Can't say I've used the globally loaded JSONs yet, so I'll trust you on this one.

One small thing: `run_parser.py` calls the now deleted `add_jsons_to_global()` and thus fails instantly.

2020-05-12 16:19 UTC, brather1ng commented on RePoE/__init__.py
> +from RePoE.parser.modules.crafting_bench_options import crafting_bench_options
These two imports aren't used, looks like leftovers

2020-05-12 20:31 UTC, NickRyder commented
Instead of calling a function by hand after calling `run_parser` I now just explicitly reload the whole module.

2020-05-13 16:32 UTC, brather1ng approved these changes
Looks good now

2020-05-13 16:32 UTC, merged